// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWGkhxLCkSiTkyQrnD2nb4JsBspVyyb68',
    appId: '1:145262125390:web:d5750ef4d06a2cca6cbe1f',
    messagingSenderId: '145262125390',
    projectId: 'masroof-661cb',
    authDomain: 'masroof-661cb.firebaseapp.com',
    storageBucket: 'masroof-661cb.firebasestorage.app',
    measurementId: 'G-5QPHN9NL6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAHSjnTC3tSj0nhGopPAyhMPHn-Yt7m8c',
    appId: '1:145262125390:android:0360cddb179b35f96cbe1f',
    messagingSenderId: '145262125390',
    projectId: 'masroof-661cb',
    storageBucket: 'masroof-661cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtScFaeeo9nFIj9AJC6IPQnpewGEtqvAQ',
    appId: '1:145262125390:ios:269e292f4d49b57f6cbe1f',
    messagingSenderId: '145262125390',
    projectId: 'masroof-661cb',
    storageBucket: 'masroof-661cb.firebasestorage.app',
    iosBundleId: 'com.example.masroof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtScFaeeo9nFIj9AJC6IPQnpewGEtqvAQ',
    appId: '1:145262125390:ios:269e292f4d49b57f6cbe1f',
    messagingSenderId: '145262125390',
    projectId: 'masroof-661cb',
    storageBucket: 'masroof-661cb.firebasestorage.app',
    iosBundleId: 'com.example.masroof',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWGkhxLCkSiTkyQrnD2nb4JsBspVyyb68',
    appId: '1:145262125390:web:952bc671082d82db6cbe1f',
    messagingSenderId: '145262125390',
    projectId: 'masroof-661cb',
    authDomain: 'masroof-661cb.firebaseapp.com',
    storageBucket: 'masroof-661cb.firebasestorage.app',
    measurementId: 'G-44G2QSZMTS',
  );
}
